import bcrypt from 'bcryptjs';
import { User, Warehouse, Product, Inventory, Order, Payment, Notification } from '../../shared/types.ts';

const hashPassword = (password: string) => bcrypt.hashSync(password, 10);

export const seedUsers: User[] = [
  // 1. Admin
  {
    id: 'USR-ADMIN-01',
    name: 'Admin Manager',
    email: 'admin@example.com',
    password: hashPassword('Admin@123'),
    role: 'admin',
    phone: '+91 98765 43210',
    address: {
      street: '401 Executive Heights, Financial District',
      city: 'Hyderabad',
      state: 'Telangana',
      zipCode: '500032',
      country: 'India',
    },
    createdAt: '2026-01-10T09:00:00.000Z',
  },
  // 2. Primary Customer
  {
    id: 'USR-CUST-01',
    name: 'Tanmayi Sharma',
    email: 'customer@example.com',
    password: hashPassword('Customer@123'),
    role: 'customer',
    phone: '+91 91234 56789',
    address: {
      street: 'Plot 42, Jubilee Hills Road No. 36',
      city: 'Hyderabad',
      state: 'Telangana',
      zipCode: '500033',
      country: 'India',
    },
    createdAt: '2026-02-15T11:20:00.000Z',
  },
  // 3. Warehouse Manager
  {
    id: 'USR-WM-01',
    name: 'Kiran Varma',
    email: 'warehouse@example.com',
    password: hashPassword('Warehouse@123'),
    role: 'warehouse_manager',
    assignedWarehouseId: 'WH-HYD',
    phone: '+91 94401 23456',
    address: {
      street: 'Logistics Park, Shamshabad',
      city: 'Hyderabad',
      state: 'Telangana',
      zipCode: '501218',
      country: 'India',
    },
    createdAt: '2026-02-01T08:00:00.000Z',
  },
  // 4. Additional Customers
  {
    id: 'USR-CUST-02',
    name: 'John Doe',
    email: 'john@example.com',
    password: hashPassword('Customer@123'),
    role: 'customer',
    phone: '+91 98480 11223',
    address: {
      street: '12 MG Road, Governorpet',
      city: 'Vijayawada',
      state: 'Andhra Pradesh',
      zipCode: '520002',
      country: 'India',
    },
    createdAt: '2026-02-20T14:15:00.000Z',
  },
  {
    id: 'USR-CUST-03',
    name: 'Sarah Connor',
    email: 'sarah@example.com',
    password: hashPassword('Customer@123'),
    role: 'customer',
    phone: '+91 99123 44556',
    address: {
      street: 'Beach Road, Pandurangapuram',
      city: 'Visakhapatnam',
      state: 'Andhra Pradesh',
      zipCode: '530003',
      country: 'India',
    },
    createdAt: '2026-03-01T16:45:00.000Z',
  },
  {
    id: 'USR-CUST-04',
    name: 'Rajesh Kumar',
    email: 'raj@example.com',
    password: hashPassword('Customer@123'),
    role: 'customer',
    phone: '+91 97000 54321',
    address: {
      street: '55 Madhapur Main Road',
      city: 'Hyderabad',
      state: 'Telangana',
      zipCode: '500081',
      country: 'India',
    },
    createdAt: '2026-03-05T10:00:00.000Z',
  },
  {
    id: 'USR-CUST-05',
    name: 'Priya Reddy',
    email: 'priya@example.com',
    password: hashPassword('Customer@123'),
    role: 'customer',
    phone: '+91 98760 99887',
    address: {
      street: '8 Benz Circle, Revenue Ward 12',
      city: 'Vijayawada',
      state: 'Andhra Pradesh',
      zipCode: '520010',
      country: 'India',
    },
    createdAt: '2026-03-08T12:00:00.000Z',
  },
  {
    id: 'USR-CUST-06',
    name: 'Vikram Rao',
    email: 'vikram@example.com',
    password: hashPassword('Customer@123'),
    role: 'customer',
    phone: '+91 94900 12345',
    address: {
      street: 'MVP Colony, Sector 3',
      city: 'Visakhapatnam',
      state: 'Andhra Pradesh',
      zipCode: '530017',
      country: 'India',
    },
    createdAt: '2026-03-10T14:30:00.000Z',
  },
  {
    id: 'USR-CUST-07',
    name: 'Ananya S.',
    email: 'ananya@example.com',
    password: hashPassword('Customer@123'),
    role: 'customer',
    phone: '+91 91000 87654',
    address: {
      street: 'Gachibowli Stadium Road',
      city: 'Hyderabad',
      state: 'Telangana',
      zipCode: '500032',
      country: 'India',
    },
    createdAt: '2026-03-12T09:15:00.000Z',
  },
  {
    id: 'USR-CUST-08',
    name: 'Sneha Patel',
    email: 'sneha@example.com',
    password: hashPassword('Customer@123'),
    role: 'customer',
    phone: '+91 93450 67890',
    address: {
      street: 'Dwaraka Nagar, 2nd Lane',
      city: 'Visakhapatnam',
      state: 'Andhra Pradesh',
      zipCode: '530016',
      country: 'India',
    },
    createdAt: '2026-03-15T15:45:00.000Z',
  },
];

export const seedWarehouses: Warehouse[] = [
  {
    warehouseId: 'WH-HYD',
    warehouseName: 'Warehouse A – Hyderabad',
    location: 'Madhapur / HITEC City, Hyderabad, Telangana',
    status: 'ACTIVE',
    capacity: 15000,
    managerName: 'Kiran Varma',
    createdAt: '2025-11-01T00:00:00.000Z',
  },
  {
    warehouseId: 'WH-VJA',
    warehouseName: 'Warehouse B – Vijayawada',
    location: 'Auto Nagar Industrial Area, Vijayawada, Andhra Pradesh',
    status: 'ACTIVE',
    capacity: 10000,
    managerName: 'Suresh Babu',
    createdAt: '2025-11-15T00:00:00.000Z',
  },
  {
    warehouseId: 'WH-VSKP',
    warehouseName: 'Warehouse C – Visakhapatnam',
    location: 'Gajuwaka Port Corridor, Visakhapatnam, Andhra Pradesh',
    status: 'ACTIVE',
    capacity: 12500,
    managerName: 'Ramesh Naidu',
    createdAt: '2025-12-01T00:00:00.000Z',
  },
];

export const seedProducts: Product[] = [
  // 1. Laptops
  {
    productId: 'PROD-101',
    sku: 'LAP-PRO-16M3',
    productName: 'ProBook Ultra 16 M3',
    description: '16.2-inch 3.4K Liquid Retina XDR OLED, 16-Core Neural Engine, 32GB Unified RAM, 1TB NVMe Gen4 SSD. Engineered for software engineers and creators.',
    category: 'Laptops',
    price: 89999,
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80',
    stockQuantity: 17, // HYD: 10, VJA: 5, VSKP: 2
    warehouseId: 'WH-HYD',
    rating: 4.9,
    status: 'ACTIVE',
    createdAt: '2026-01-01T08:00:00.000Z',
    updatedAt: '2026-03-01T08:00:00.000Z',
  },
  // 2. Mobiles
  {
    productId: 'PROD-102',
    sku: 'MOB-NEX-5G',
    productName: 'Nexus Pro 5G Flagship',
    description: '6.7-inch 120Hz LTPO AMOLED, 200MP OIS Camera, Snapdragon 8 Gen 3, 12GB RAM, 256GB storage with 5000mAh battery and 120W HyperCharge.',
    category: 'Mobiles',
    price: 54999,
    image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=800&q=80',
    stockQuantity: 10, // HYD: 0, VJA: 8, VSKP: 2 (Demo test product B!)
    warehouseId: 'WH-VJA',
    rating: 4.8,
    status: 'ACTIVE',
    createdAt: '2026-01-02T08:00:00.000Z',
    updatedAt: '2026-03-01T08:00:00.000Z',
  },
  // 3. Electronics / Audio
  {
    productId: 'PROD-103',
    sku: 'AUD-AERO-ANC',
    productName: 'AeroSound ANC Wireless Headphones',
    description: 'Active Noise Cancellation up to 45dB, Hi-Res Wireless Audio, spatial audio tracking, ultra-plush memory foam cushions, 40-hour playback.',
    category: 'Electronics',
    price: 12499,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    stockQuantity: 35, // HYD: 15, VJA: 10, VSKP: 10
    warehouseId: 'WH-HYD',
    rating: 4.7,
    status: 'ACTIVE',
    createdAt: '2026-01-03T08:00:00.000Z',
    updatedAt: '2026-03-01T08:00:00.000Z',
  },
  // 4. Accessories / Keyboard
  {
    productId: 'PROD-104',
    sku: 'ACC-TAC-RGB',
    productName: 'Tactile RGB Mechanical Keyboard',
    description: 'Hot-swappable custom tactile switches, sound dampening foam, CNC aluminum chassis, per-key RGB backlight, tri-mode 2.4G/Bluetooth/USB-C.',
    category: 'Accessories',
    price: 5499,
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
    stockQuantity: 8, // HYD: 3, VJA: 0, VSKP: 5 (Demo test product C!)
    warehouseId: 'WH-VSKP',
    rating: 4.9,
    status: 'ACTIVE',
    createdAt: '2026-01-04T08:00:00.000Z',
    updatedAt: '2026-03-01T08:00:00.000Z',
  },
  // 5. Accessories / Mouse
  {
    productId: 'PROD-105',
    sku: 'ACC-PREC-MOU',
    productName: 'Precision Wireless Laser Mouse',
    description: 'Ergonomic sculptured thumb rest, 8000 DPI Darkfield glass tracking, electromagnetic MagSpeed scrolling wheel, multi-device instant switching.',
    category: 'Accessories',
    price: 2799,
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=800&q=80',
    stockQuantity: 32, // HYD: 12, VJA: 8, VSKP: 12
    warehouseId: 'WH-HYD',
    rating: 4.6,
    status: 'ACTIVE',
    createdAt: '2026-01-05T08:00:00.000Z',
    updatedAt: '2026-03-01T08:00:00.000Z',
  },
  // 6. Accessories / Smart Watch
  {
    productId: 'PROD-106',
    sku: 'ACC-WAT-PULSE',
    productName: 'PulseFit Active Health Smartwatch',
    description: 'Sapphire glass 1.4-inch AMOLED, ECG sensor, SpO2 monitor, dual-frequency GPS navigation, 7-day battery life, 5ATM water resistance.',
    category: 'Accessories',
    price: 8999,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
    stockQuantity: 24, // HYD: 8, VJA: 6, VSKP: 10
    warehouseId: 'WH-VSKP',
    rating: 4.7,
    status: 'ACTIVE',
    createdAt: '2026-01-06T08:00:00.000Z',
    updatedAt: '2026-03-01T08:00:00.000Z',
  },
  // 7. Electronics / Monitor
  {
    productId: 'PROD-107',
    sku: 'ELE-MON-4K27',
    productName: 'UltraView 4K IPS Gaming Monitor 27"',
    description: '27-inch 4K IPS 160Hz refresh rate, 1ms response, HDR600, 99% DCI-P3 color gamut, dual HDMI 2.1 + USB-C 90W PD port.',
    category: 'Electronics',
    price: 28999,
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80',
    stockQuantity: 18, // HYD: 6, VJA: 8, VSKP: 4
    warehouseId: 'WH-VJA',
    rating: 4.8,
    status: 'ACTIVE',
    createdAt: '2026-01-07T08:00:00.000Z',
    updatedAt: '2026-03-01T08:00:00.000Z',
  },
  // 8. Laptops / Tablet
  {
    productId: 'PROD-108',
    sku: 'LAP-TAB-11PRO',
    productName: 'TabMaster Pro 11" OLED Tablet',
    description: '11-inch 2.8K 120Hz OLED screen, stylus pressure sensitivity, Octa-Core chip, 8GB RAM, 128GB ROM, quad stereo speakers.',
    category: 'Laptops',
    price: 42999,
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=800&q=80',
    stockQuantity: 15, // HYD: 5, VJA: 6, VSKP: 4
    warehouseId: 'WH-HYD',
    rating: 4.7,
    status: 'ACTIVE',
    createdAt: '2026-01-08T08:00:00.000Z',
    updatedAt: '2026-03-01T08:00:00.000Z',
  },
  // 9. Accessories / Power Bank
  {
    productId: 'PROD-109',
    sku: 'ACC-POW-20K65W',
    productName: 'HyperCharge 20000mAh 65W GaN Power Bank',
    description: 'High capacity 20,000mAh battery pack with 65W fast USB-C PD output. Charges laptops, tablets, and phones at full speed with digital LED display.',
    category: 'Accessories',
    price: 3499,
    image: 'https://images.unsplash.com/photo-1609592426508-cc82110c920f?auto=format&fit=crop&w=800&q=80',
    stockQuantity: 28, // HYD: 10, VJA: 10, VSKP: 8
    warehouseId: 'WH-VJA',
    rating: 4.6,
    status: 'ACTIVE',
    createdAt: '2026-01-09T08:00:00.000Z',
    updatedAt: '2026-03-01T08:00:00.000Z',
  },
  // 10. Electronics / Speaker
  {
    productId: 'PROD-110',
    sku: 'ELE-SPK-360BASS',
    productName: 'BoomBass 360° Waterproof Speaker',
    description: 'IP67 waterproof and dustproof rugged bluetooth speaker with dual passive bass radiators, 360-degree acoustic dispersion, and 24hr battery life.',
    category: 'Electronics',
    price: 4999,
    image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
    stockQuantity: 22, // HYD: 8, VJA: 7, VSKP: 7
    warehouseId: 'WH-HYD',
    rating: 4.8,
    status: 'ACTIVE',
    createdAt: '2026-01-10T08:00:00.000Z',
    updatedAt: '2026-03-01T08:00:00.000Z',
  },
  // 11. Home Appliances / Smart TV
  {
    productId: 'PROD-111',
    sku: 'HOM-TV-55QLED',
    productName: 'VisionX 55" 4K QLED Dolby Vision TV',
    description: 'Quantum Dot 4K display, 120Hz native refresh rate, Dolby Vision IQ, 50W Dolby Atmos front-firing soundbar, Google TV OS with voice assistant.',
    category: 'Home Appliances',
    price: 48999,
    image: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=800&q=80',
    stockQuantity: 8, // HYD: 3, VJA: 3, VSKP: 2
    warehouseId: 'WH-HYD',
    rating: 4.8,
    status: 'ACTIVE',
    createdAt: '2026-01-11T08:00:00.000Z',
    updatedAt: '2026-03-01T08:00:00.000Z',
  },
  // 12. Home Appliances / Air Purifier
  {
    productId: 'PROD-112',
    sku: 'HOM-AIR-HEPA',
    productName: 'PureBreeze HEPA Pro Air Purifier',
    description: 'True HEPA H13 filtration capturing 99.97% of airborne PM2.5 particulates, CADR 450 m³/h, laser particle scanner, quiet night mode at 22dB.',
    category: 'Home Appliances',
    price: 11999,
    image: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?auto=format&fit=crop&w=800&q=80',
    stockQuantity: 12, // HYD: 4, VJA: 4, VSKP: 4
    warehouseId: 'WH-VJA',
    rating: 4.6,
    status: 'ACTIVE',
    createdAt: '2026-01-12T08:00:00.000Z',
    updatedAt: '2026-03-01T08:00:00.000Z',
  },
  // 13. Home Appliances / Robot Vacuum
  {
    productId: 'PROD-113',
    sku: 'HOM-VAC-BOT',
    productName: 'CleanBot Laser Mapping Smart Vacuum',
    description: 'LiDAR precision navigation mapping, 4000Pa suction power, motorized sonic mopping, auto carpet boost, app control with virtual boundary zones.',
    category: 'Home Appliances',
    price: 24999,
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80',
    stockQuantity: 9, // HYD: 3, VJA: 3, VSKP: 3
    warehouseId: 'WH-VSKP',
    rating: 4.7,
    status: 'ACTIVE',
    createdAt: '2026-01-13T08:00:00.000Z',
    updatedAt: '2026-03-01T08:00:00.000Z',
  },
  // 14. Accessories / Fast Charger
  {
    productId: 'PROD-114',
    sku: 'ACC-CHG-100WGAN',
    productName: 'TurboCharge 100W Multi-Port GaN Charger',
    description: 'Ultra-compact Gallium Nitride III wall charger with 3x USB-C and 1x USB-A ports. Powers laptop, tablet, and phones simultaneously safely.',
    category: 'Accessories',
    price: 2299,
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=80',
    stockQuantity: 3, // Low stock demo SKU (HYD: 2, VJA: 0, VSKP: 1)
    warehouseId: 'WH-HYD',
    rating: 4.9,
    status: 'ACTIVE',
    createdAt: '2026-01-14T08:00:00.000Z',
    updatedAt: '2026-03-01T08:00:00.000Z',
  },
  // 15. Electronics / Storage
  {
    productId: 'PROD-115',
    sku: 'ELE-SSD-2TBNVME',
    productName: 'HyperSpeed 2TB Gen4 PCIe M.2 SSD',
    description: 'Blistering internal solid state drive read speeds up to 7400 MB/s, 6800 MB/s write. Graphene copper heatsink for thermal throttle protection.',
    category: 'Electronics',
    price: 14299,
    image: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=800&q=80',
    stockQuantity: 14, // HYD: 4, VJA: 6, VSKP: 4
    warehouseId: 'WH-VJA',
    rating: 4.9,
    status: 'ACTIVE',
    createdAt: '2026-01-15T08:00:00.000Z',
    updatedAt: '2026-03-01T08:00:00.000Z',
  },
  // 16. Mobiles
  {
    productId: 'PROD-116',
    sku: 'MOB-NEO-128GB',
    productName: 'NeoPhone Prime 128GB',
    description: '6.5-inch 90Hz FHD+ display, 50MP AI Dual Camera, 5000mAh battery, 33W fast charging, side-mounted fingerprint sensor.',
    category: 'Mobiles',
    price: 19999,
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80',
    stockQuantity: 20, // HYD: 8, VJA: 6, VSKP: 6
    warehouseId: 'WH-HYD',
    rating: 4.5,
    status: 'ACTIVE',
    createdAt: '2026-01-16T08:00:00.000Z',
    updatedAt: '2026-03-01T08:00:00.000Z',
  },
];

export const seedInventory: Inventory[] = [
  // PROD-101 (Laptop): Total 17 -> HYD: 10, VJA: 5, VSKP: 2
  { inventoryId: 'INV-101-HYD', productId: 'PROD-101', warehouseId: 'WH-HYD', quantity: 10, reservedQuantity: 0, availableQuantity: 10 },
  { inventoryId: 'INV-101-VJA', productId: 'PROD-101', warehouseId: 'WH-VJA', quantity: 5, reservedQuantity: 0, availableQuantity: 5 },
  { inventoryId: 'INV-101-VSKP', productId: 'PROD-101', warehouseId: 'WH-VSKP', quantity: 2, reservedQuantity: 0, availableQuantity: 2 },

  // PROD-102 (Smartphone): Total 10 -> HYD: 0, VJA: 8, VSKP: 2 (Demo Product B)
  { inventoryId: 'INV-102-HYD', productId: 'PROD-102', warehouseId: 'WH-HYD', quantity: 0, reservedQuantity: 0, availableQuantity: 0 },
  { inventoryId: 'INV-102-VJA', productId: 'PROD-102', warehouseId: 'WH-VJA', quantity: 8, reservedQuantity: 0, availableQuantity: 8 },
  { inventoryId: 'INV-102-VSKP', productId: 'PROD-102', warehouseId: 'WH-VSKP', quantity: 2, reservedQuantity: 0, availableQuantity: 2 },

  // PROD-103 (Headphones): Total 35 -> HYD: 15, VJA: 10, VSKP: 10
  { inventoryId: 'INV-103-HYD', productId: 'PROD-103', warehouseId: 'WH-HYD', quantity: 15, reservedQuantity: 0, availableQuantity: 15 },
  { inventoryId: 'INV-103-VJA', productId: 'PROD-103', warehouseId: 'WH-VJA', quantity: 10, reservedQuantity: 0, availableQuantity: 10 },
  { inventoryId: 'INV-103-VSKP', productId: 'PROD-103', warehouseId: 'WH-VSKP', quantity: 10, reservedQuantity: 0, availableQuantity: 10 },

  // PROD-104 (Keyboard): Total 8 -> HYD: 3, VJA: 0, VSKP: 5 (Demo Product C)
  { inventoryId: 'INV-104-HYD', productId: 'PROD-104', warehouseId: 'WH-HYD', quantity: 3, reservedQuantity: 0, availableQuantity: 3 },
  { inventoryId: 'INV-104-VJA', productId: 'PROD-104', warehouseId: 'WH-VJA', quantity: 0, reservedQuantity: 0, availableQuantity: 0 },
  { inventoryId: 'INV-104-VSKP', productId: 'PROD-104', warehouseId: 'WH-VSKP', quantity: 5, reservedQuantity: 0, availableQuantity: 5 },

  // PROD-105 (Mouse): Total 32 -> HYD: 12, VJA: 8, VSKP: 12
  { inventoryId: 'INV-105-HYD', productId: 'PROD-105', warehouseId: 'WH-HYD', quantity: 12, reservedQuantity: 0, availableQuantity: 12 },
  { inventoryId: 'INV-105-VJA', productId: 'PROD-105', warehouseId: 'WH-VJA', quantity: 8, reservedQuantity: 0, availableQuantity: 8 },
  { inventoryId: 'INV-105-VSKP', productId: 'PROD-105', warehouseId: 'WH-VSKP', quantity: 12, reservedQuantity: 0, availableQuantity: 12 },

  // PROD-106 (Smart Watch): Total 24 -> HYD: 8, VJA: 6, VSKP: 10
  { inventoryId: 'INV-106-HYD', productId: 'PROD-106', warehouseId: 'WH-HYD', quantity: 8, reservedQuantity: 0, availableQuantity: 8 },
  { inventoryId: 'INV-106-VJA', productId: 'PROD-106', warehouseId: 'WH-VJA', quantity: 6, reservedQuantity: 0, availableQuantity: 6 },
  { inventoryId: 'INV-106-VSKP', productId: 'PROD-106', warehouseId: 'WH-VSKP', quantity: 10, reservedQuantity: 0, availableQuantity: 10 },

  // PROD-107 (Monitor): Total 18 -> HYD: 6, VJA: 8, VSKP: 4
  { inventoryId: 'INV-107-HYD', productId: 'PROD-107', warehouseId: 'WH-HYD', quantity: 6, reservedQuantity: 0, availableQuantity: 6 },
  { inventoryId: 'INV-107-VJA', productId: 'PROD-107', warehouseId: 'WH-VJA', quantity: 8, reservedQuantity: 0, availableQuantity: 8 },
  { inventoryId: 'INV-107-VSKP', productId: 'PROD-107', warehouseId: 'WH-VSKP', quantity: 4, reservedQuantity: 0, availableQuantity: 4 },

  // PROD-108 (Tablet): Total 15 -> HYD: 5, VJA: 6, VSKP: 4
  { inventoryId: 'INV-108-HYD', productId: 'PROD-108', warehouseId: 'WH-HYD', quantity: 5, reservedQuantity: 0, availableQuantity: 5 },
  { inventoryId: 'INV-108-VJA', productId: 'PROD-108', warehouseId: 'WH-VJA', quantity: 6, reservedQuantity: 0, availableQuantity: 6 },
  { inventoryId: 'INV-108-VSKP', productId: 'PROD-108', warehouseId: 'WH-VSKP', quantity: 4, reservedQuantity: 0, availableQuantity: 4 },

  // PROD-109 (Power Bank): Total 28 -> HYD: 10, VJA: 10, VSKP: 8
  { inventoryId: 'INV-109-HYD', productId: 'PROD-109', warehouseId: 'WH-HYD', quantity: 10, reservedQuantity: 0, availableQuantity: 10 },
  { inventoryId: 'INV-109-VJA', productId: 'PROD-109', warehouseId: 'WH-VJA', quantity: 10, reservedQuantity: 0, availableQuantity: 10 },
  { inventoryId: 'INV-109-VSKP', productId: 'PROD-109', warehouseId: 'WH-VSKP', quantity: 8, reservedQuantity: 0, availableQuantity: 8 },

  // PROD-110 (Speaker): Total 22 -> HYD: 8, VJA: 7, VSKP: 7
  { inventoryId: 'INV-110-HYD', productId: 'PROD-110', warehouseId: 'WH-HYD', quantity: 8, reservedQuantity: 0, availableQuantity: 8 },
  { inventoryId: 'INV-110-VJA', productId: 'PROD-110', warehouseId: 'WH-VJA', quantity: 7, reservedQuantity: 0, availableQuantity: 7 },
  { inventoryId: 'INV-110-VSKP', productId: 'PROD-110', warehouseId: 'WH-VSKP', quantity: 7, reservedQuantity: 0, availableQuantity: 7 },

  // PROD-111 (Smart TV): Total 8 -> HYD: 3, VJA: 3, VSKP: 2
  { inventoryId: 'INV-111-HYD', productId: 'PROD-111', warehouseId: 'WH-HYD', quantity: 3, reservedQuantity: 0, availableQuantity: 3 },
  { inventoryId: 'INV-111-VJA', productId: 'PROD-111', warehouseId: 'WH-VJA', quantity: 3, reservedQuantity: 0, availableQuantity: 3 },
  { inventoryId: 'INV-111-VSKP', productId: 'PROD-111', warehouseId: 'WH-VSKP', quantity: 2, reservedQuantity: 0, availableQuantity: 2 },

  // PROD-112 (Air Purifier): Total 12 -> HYD: 4, VJA: 4, VSKP: 4
  { inventoryId: 'INV-112-HYD', productId: 'PROD-112', warehouseId: 'WH-HYD', quantity: 4, reservedQuantity: 0, availableQuantity: 4 },
  { inventoryId: 'INV-112-VJA', productId: 'PROD-112', warehouseId: 'WH-VJA', quantity: 4, reservedQuantity: 0, availableQuantity: 4 },
  { inventoryId: 'INV-112-VSKP', productId: 'PROD-112', warehouseId: 'WH-VSKP', quantity: 4, reservedQuantity: 0, availableQuantity: 4 },

  // PROD-113 (Robot Vacuum): Total 9 -> HYD: 3, VJA: 3, VSKP: 3
  { inventoryId: 'INV-113-HYD', productId: 'PROD-113', warehouseId: 'WH-HYD', quantity: 3, reservedQuantity: 0, availableQuantity: 3 },
  { inventoryId: 'INV-113-VJA', productId: 'PROD-113', warehouseId: 'WH-VJA', quantity: 3, reservedQuantity: 0, availableQuantity: 3 },
  { inventoryId: 'INV-113-VSKP', productId: 'PROD-113', warehouseId: 'WH-VSKP', quantity: 3, reservedQuantity: 0, availableQuantity: 3 },

  // PROD-114 (GaN Fast Charger - Critical Low Stock): Total 3 -> HYD: 2, VJA: 0, VSKP: 1
  { inventoryId: 'INV-114-HYD', productId: 'PROD-114', warehouseId: 'WH-HYD', quantity: 2, reservedQuantity: 0, availableQuantity: 2 },
  { inventoryId: 'INV-114-VJA', productId: 'PROD-114', warehouseId: 'WH-VJA', quantity: 0, reservedQuantity: 0, availableQuantity: 0 },
  { inventoryId: 'INV-114-VSKP', productId: 'PROD-114', warehouseId: 'WH-VSKP', quantity: 1, reservedQuantity: 0, availableQuantity: 1 },

  // PROD-115 (NVMe SSD): Total 14 -> HYD: 4, VJA: 6, VSKP: 4
  { inventoryId: 'INV-115-HYD', productId: 'PROD-115', warehouseId: 'WH-HYD', quantity: 4, reservedQuantity: 0, availableQuantity: 4 },
  { inventoryId: 'INV-115-VJA', productId: 'PROD-115', warehouseId: 'WH-VJA', quantity: 6, reservedQuantity: 0, availableQuantity: 6 },
  { inventoryId: 'INV-115-VSKP', productId: 'PROD-115', warehouseId: 'WH-VSKP', quantity: 4, reservedQuantity: 0, availableQuantity: 4 },

  // PROD-116 (NeoPhone): Total 20 -> HYD: 8, VJA: 6, VSKP: 6
  { inventoryId: 'INV-116-HYD', productId: 'PROD-116', warehouseId: 'WH-HYD', quantity: 8, reservedQuantity: 0, availableQuantity: 8 },
  { inventoryId: 'INV-116-VJA', productId: 'PROD-116', warehouseId: 'WH-VJA', quantity: 6, reservedQuantity: 0, availableQuantity: 6 },
  { inventoryId: 'INV-116-VSKP', productId: 'PROD-116', warehouseId: 'WH-VSKP', quantity: 6, reservedQuantity: 0, availableQuantity: 6 },
];

export const seedOrders: Order[] = [
  // 1. Delivered order
  {
    orderId: 'ORD-9821',
    customerId: 'USR-CUST-01',
    customerName: 'Tanmayi Sharma',
    customerEmail: 'customer@example.com',
    customerPhone: '+91 91234 56789',
    orderItems: [
      {
        productId: 'PROD-103',
        productName: 'AeroSound ANC Wireless Headphones',
        price: 12499,
        quantity: 1,
        image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
        warehouseFulfillments: [{ warehouseId: 'WH-HYD', warehouseName: 'Warehouse A – Hyderabad', quantity: 1 }],
      },
    ],
    totalAmount: 12499,
    shippingAddress: {
      street: 'Plot 42, Jubilee Hills Road No. 36',
      city: 'Hyderabad',
      state: 'Telangana',
      zipCode: '500033',
      country: 'India',
    },
    orderStatus: 'DELIVERED',
    paymentStatus: 'SUCCESS',
    paymentMethod: 'UPI',
    fulfillmentType: 'SINGLE_WAREHOUSE',
    fulfillmentDetails: [
      {
        warehouseId: 'WH-HYD',
        warehouseName: 'Warehouse A – Hyderabad',
        location: 'Madhapur / HITEC City, Hyderabad, Telangana',
        status: 'DELIVERED',
        items: [{ productId: 'PROD-103', productName: 'AeroSound ANC Wireless Headphones', quantity: 1 }],
      },
    ],
    expectedDeliveryDate: '2026-03-04T18:00:00.000Z',
    createdAt: '2026-03-01T10:14:00.000Z',
    updatedAt: '2026-03-04T16:30:00.000Z',
  },
  // 2. Shipped order
  {
    orderId: 'ORD-9822',
    customerId: 'USR-CUST-02',
    customerName: 'John Doe',
    customerEmail: 'john@example.com',
    customerPhone: '+91 98480 11223',
    orderItems: [
      {
        productId: 'PROD-101',
        productName: 'ProBook Ultra 16 M3',
        price: 89999,
        quantity: 1,
        image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80',
        warehouseFulfillments: [{ warehouseId: 'WH-HYD', warehouseName: 'Warehouse A – Hyderabad', quantity: 1 }],
      },
      {
        productId: 'PROD-105',
        productName: 'Precision Wireless Laser Mouse',
        price: 2799,
        quantity: 1,
        image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=800&q=80',
        warehouseFulfillments: [{ warehouseId: 'WH-HYD', warehouseName: 'Warehouse A – Hyderabad', quantity: 1 }],
      },
    ],
    totalAmount: 92798,
    shippingAddress: {
      street: '12 MG Road, Governorpet',
      city: 'Vijayawada',
      state: 'Andhra Pradesh',
      zipCode: '520002',
      country: 'India',
    },
    orderStatus: 'SHIPPED',
    paymentStatus: 'SUCCESS',
    paymentMethod: 'Credit Card',
    fulfillmentType: 'SINGLE_WAREHOUSE',
    fulfillmentDetails: [
      {
        warehouseId: 'WH-HYD',
        warehouseName: 'Warehouse A – Hyderabad',
        location: 'Madhapur / HITEC City, Hyderabad, Telangana',
        status: 'SHIPPED',
        items: [
          { productId: 'PROD-101', productName: 'ProBook Ultra 16 M3', quantity: 1 },
          { productId: 'PROD-105', productName: 'Precision Wireless Laser Mouse', quantity: 1 },
        ],
      },
    ],
    expectedDeliveryDate: '2026-03-07T18:00:00.000Z',
    createdAt: '2026-03-04T12:00:00.000Z',
    updatedAt: '2026-03-05T09:15:00.000Z',
  },
  // 3. Packed order awaiting pickup
  {
    orderId: 'ORD-9823',
    customerId: 'USR-CUST-03',
    customerName: 'Sarah Connor',
    customerEmail: 'sarah@example.com',
    customerPhone: '+91 99123 44556',
    orderItems: [
      {
        productId: 'PROD-107',
        productName: 'UltraView 4K IPS Gaming Monitor 27"',
        price: 28999,
        quantity: 1,
        image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80',
        warehouseFulfillments: [{ warehouseId: 'WH-VJA', warehouseName: 'Warehouse B – Vijayawada', quantity: 1 }],
      },
    ],
    totalAmount: 28999,
    shippingAddress: {
      street: 'Beach Road, Pandurangapuram',
      city: 'Visakhapatnam',
      state: 'Andhra Pradesh',
      zipCode: '530003',
      country: 'India',
    },
    orderStatus: 'PACKED',
    paymentStatus: 'SUCCESS',
    paymentMethod: 'UPI',
    fulfillmentType: 'SINGLE_WAREHOUSE',
    fulfillmentDetails: [
      {
        warehouseId: 'WH-VJA',
        warehouseName: 'Warehouse B – Vijayawada',
        location: 'Auto Nagar Industrial Area, Vijayawada, Andhra Pradesh',
        status: 'PACKED',
        items: [{ productId: 'PROD-107', productName: 'UltraView 4K IPS Gaming Monitor 27"', quantity: 1 }],
      },
    ],
    expectedDeliveryDate: '2026-03-09T18:00:00.000Z',
    createdAt: '2026-03-05T15:20:00.000Z',
    updatedAt: '2026-03-05T17:00:00.000Z',
  },
  // 4. Split order processing across Hyderabad and Vijayawada! (Example in problem statement)
  {
    orderId: 'ORD-9824',
    customerId: 'USR-CUST-01',
    customerName: 'Tanmayi Sharma',
    customerEmail: 'customer@example.com',
    customerPhone: '+91 91234 56789',
    orderItems: [
      {
        productId: 'PROD-101',
        productName: 'ProBook Ultra 16 M3',
        price: 89999,
        quantity: 2,
        warehouseFulfillments: [{ warehouseId: 'WH-HYD', warehouseName: 'Warehouse A – Hyderabad', quantity: 2 }],
      },
      {
        productId: 'PROD-102',
        productName: 'Nexus Pro 5G Flagship',
        price: 54999,
        quantity: 1,
        warehouseFulfillments: [{ warehouseId: 'WH-VJA', warehouseName: 'Warehouse B – Vijayawada', quantity: 1 }],
      },
      {
        productId: 'PROD-104',
        productName: 'Tactile RGB Mechanical Keyboard',
        price: 5499,
        quantity: 3,
        warehouseFulfillments: [{ warehouseId: 'WH-HYD', warehouseName: 'Warehouse A – Hyderabad', quantity: 3 }],
      },
    ],
    totalAmount: 251494,
    shippingAddress: {
      street: 'Plot 42, Jubilee Hills Road No. 36',
      city: 'Hyderabad',
      state: 'Telangana',
      zipCode: '500033',
      country: 'India',
    },
    orderStatus: 'PROCESSING',
    paymentStatus: 'SUCCESS',
    paymentMethod: 'Credit Card',
    fulfillmentType: 'SPLIT_ORDER',
    fulfillmentDetails: [
      {
        warehouseId: 'WH-HYD',
        warehouseName: 'Warehouse A – Hyderabad',
        location: 'Madhapur / HITEC City, Hyderabad, Telangana',
        status: 'PENDING_PACKING',
        items: [
          { productId: 'PROD-101', productName: 'ProBook Ultra 16 M3', quantity: 2 },
          { productId: 'PROD-104', productName: 'Tactile RGB Mechanical Keyboard', quantity: 3 },
        ],
      },
      {
        warehouseId: 'WH-VJA',
        warehouseName: 'Warehouse B – Vijayawada',
        location: 'Auto Nagar Industrial Area, Vijayawada, Andhra Pradesh',
        status: 'PENDING_PACKING',
        items: [{ productId: 'PROD-102', productName: 'Nexus Pro 5G Flagship', quantity: 1 }],
      },
    ],
    expectedDeliveryDate: '2026-03-10T18:00:00.000Z',
    createdAt: '2026-03-06T11:00:00.000Z',
    updatedAt: '2026-03-06T11:05:00.000Z',
  },
  // 5. Confirmed order in Visakhapatnam
  {
    orderId: 'ORD-9825',
    customerId: 'USR-CUST-04',
    customerName: 'Rajesh Kumar',
    customerEmail: 'raj@example.com',
    customerPhone: '+91 97000 54321',
    orderItems: [
      {
        productId: 'PROD-106',
        productName: 'PulseFit Active Health Smartwatch',
        price: 8999,
        quantity: 1,
        warehouseFulfillments: [{ warehouseId: 'WH-VSKP', warehouseName: 'Warehouse C – Visakhapatnam', quantity: 1 }],
      },
    ],
    totalAmount: 8999,
    shippingAddress: {
      street: '55 Madhapur Main Road',
      city: 'Hyderabad',
      state: 'Telangana',
      zipCode: '500081',
      country: 'India',
    },
    orderStatus: 'CONFIRMED',
    paymentStatus: 'SUCCESS',
    paymentMethod: 'UPI',
    fulfillmentType: 'SINGLE_WAREHOUSE',
    fulfillmentDetails: [
      {
        warehouseId: 'WH-VSKP',
        warehouseName: 'Warehouse C – Visakhapatnam',
        location: 'Gajuwaka Port Corridor, Visakhapatnam, Andhra Pradesh',
        status: 'PENDING_PACKING',
        items: [{ productId: 'PROD-106', productName: 'PulseFit Active Health Smartwatch', quantity: 1 }],
      },
    ],
    expectedDeliveryDate: '2026-03-11T18:00:00.000Z',
    createdAt: '2026-03-07T09:30:00.000Z',
    updatedAt: '2026-03-07T09:32:00.000Z',
  },
  // 6. Payment Pending order
  {
    orderId: 'ORD-9826',
    customerId: 'USR-CUST-05',
    customerName: 'Priya Reddy',
    customerEmail: 'priya@example.com',
    customerPhone: '+91 98760 99887',
    orderItems: [
      {
        productId: 'PROD-109',
        productName: 'HyperCharge 20000mAh 65W GaN Power Bank',
        price: 3499,
        quantity: 1,
        warehouseFulfillments: [{ warehouseId: 'WH-VJA', warehouseName: 'Warehouse B – Vijayawada', quantity: 1 }],
      },
    ],
    totalAmount: 3499,
    shippingAddress: {
      street: '8 Benz Circle, Revenue Ward 12',
      city: 'Vijayawada',
      state: 'Andhra Pradesh',
      zipCode: '520010',
      country: 'India',
    },
    orderStatus: 'PAYMENT_PENDING',
    paymentStatus: 'FAILED',
    paymentMethod: 'Debit Card',
    fulfillmentType: 'SINGLE_WAREHOUSE',
    fulfillmentDetails: [
      {
        warehouseId: 'WH-VJA',
        warehouseName: 'Warehouse B – Vijayawada',
        location: 'Auto Nagar Industrial Area, Vijayawada, Andhra Pradesh',
        status: 'PENDING_PACKING',
        items: [{ productId: 'PROD-109', productName: 'HyperCharge 20000mAh 65W GaN Power Bank', quantity: 1 }],
      },
    ],
    expectedDeliveryDate: '2026-03-12T18:00:00.000Z',
    createdAt: '2026-03-07T14:00:00.000Z',
    updatedAt: '2026-03-07T14:01:00.000Z',
  },
  // 7. Out for Delivery order
  {
    orderId: 'ORD-9827',
    customerId: 'USR-CUST-06',
    customerName: 'Vikram Rao',
    customerEmail: 'vikram@example.com',
    customerPhone: '+91 94900 12345',
    orderItems: [
      {
        productId: 'PROD-110',
        productName: 'BoomBass 360° Waterproof Speaker',
        price: 4999,
        quantity: 1,
        warehouseFulfillments: [{ warehouseId: 'WH-HYD', warehouseName: 'Warehouse A – Hyderabad', quantity: 1 }],
      },
    ],
    totalAmount: 4999,
    shippingAddress: {
      street: 'MVP Colony, Sector 3',
      city: 'Visakhapatnam',
      state: 'Andhra Pradesh',
      zipCode: '530017',
      country: 'India',
    },
    orderStatus: 'OUT_FOR_DELIVERY',
    paymentStatus: 'SUCCESS',
    paymentMethod: 'Cash on Delivery',
    fulfillmentType: 'SINGLE_WAREHOUSE',
    fulfillmentDetails: [
      {
        warehouseId: 'WH-HYD',
        warehouseName: 'Warehouse A – Hyderabad',
        location: 'Madhapur / HITEC City, Hyderabad, Telangana',
        status: 'SHIPPED',
        items: [{ productId: 'PROD-110', productName: 'BoomBass 360° Waterproof Speaker', quantity: 1 }],
      },
    ],
    expectedDeliveryDate: '2026-03-08T18:00:00.000Z',
    createdAt: '2026-03-05T08:00:00.000Z',
    updatedAt: '2026-03-08T07:30:00.000Z',
  },
  // 8. Cancelled order
  {
    orderId: 'ORD-9828',
    customerId: 'USR-CUST-07',
    customerName: 'Ananya S.',
    customerEmail: 'ananya@example.com',
    customerPhone: '+91 91000 87654',
    orderItems: [
      {
        productId: 'PROD-112',
        productName: 'PureBreeze HEPA Pro Air Purifier',
        price: 11999,
        quantity: 1,
        warehouseFulfillments: [{ warehouseId: 'WH-VJA', warehouseName: 'Warehouse B – Vijayawada', quantity: 1 }],
      },
    ],
    totalAmount: 11999,
    shippingAddress: {
      street: 'Gachibowli Stadium Road',
      city: 'Hyderabad',
      state: 'Telangana',
      zipCode: '500032',
      country: 'India',
    },
    orderStatus: 'CANCELLED',
    paymentStatus: 'REFUNDED',
    paymentMethod: 'UPI',
    fulfillmentType: 'SINGLE_WAREHOUSE',
    fulfillmentDetails: [
      {
        warehouseId: 'WH-VJA',
        warehouseName: 'Warehouse B – Vijayawada',
        location: 'Auto Nagar Industrial Area, Vijayawada, Andhra Pradesh',
        status: 'PENDING_PACKING',
        items: [{ productId: 'PROD-112', productName: 'PureBreeze HEPA Pro Air Purifier', quantity: 1 }],
      },
    ],
    createdAt: '2026-03-06T15:00:00.000Z',
    updatedAt: '2026-03-06T16:20:00.000Z',
  },
  // 9. Delivered order
  {
    orderId: 'ORD-9829',
    customerId: 'USR-CUST-08',
    customerName: 'Sneha Patel',
    customerEmail: 'sneha@example.com',
    customerPhone: '+91 93450 67890',
    orderItems: [
      {
        productId: 'PROD-115',
        productName: 'HyperSpeed 2TB Gen4 PCIe M.2 SSD',
        price: 14299,
        quantity: 1,
        warehouseFulfillments: [{ warehouseId: 'WH-VJA', warehouseName: 'Warehouse B – Vijayawada', quantity: 1 }],
      },
    ],
    totalAmount: 14299,
    shippingAddress: {
      street: 'Dwaraka Nagar, 2nd Lane',
      city: 'Visakhapatnam',
      state: 'Andhra Pradesh',
      zipCode: '530016',
      country: 'India',
    },
    orderStatus: 'DELIVERED',
    paymentStatus: 'SUCCESS',
    paymentMethod: 'Debit Card',
    fulfillmentType: 'SINGLE_WAREHOUSE',
    fulfillmentDetails: [
      {
        warehouseId: 'WH-VJA',
        warehouseName: 'Warehouse B – Vijayawada',
        location: 'Auto Nagar Industrial Area, Vijayawada, Andhra Pradesh',
        status: 'DELIVERED',
        items: [{ productId: 'PROD-115', productName: 'HyperSpeed 2TB Gen4 PCIe M.2 SSD', quantity: 1 }],
      },
    ],
    expectedDeliveryDate: '2026-03-07T18:00:00.000Z',
    createdAt: '2026-03-04T16:00:00.000Z',
    updatedAt: '2026-03-07T14:10:00.000Z',
  },
  // 10. Newly Placed order
  {
    orderId: 'ORD-9830',
    customerId: 'USR-CUST-01',
    customerName: 'Tanmayi Sharma',
    customerEmail: 'customer@example.com',
    customerPhone: '+91 91234 56789',
    orderItems: [
      {
        productId: 'PROD-116',
        productName: 'NeoPhone Prime 128GB',
        price: 19999,
        quantity: 1,
        warehouseFulfillments: [{ warehouseId: 'WH-HYD', warehouseName: 'Warehouse A – Hyderabad', quantity: 1 }],
      },
    ],
    totalAmount: 19999,
    shippingAddress: {
      street: 'Plot 42, Jubilee Hills Road No. 36',
      city: 'Hyderabad',
      state: 'Telangana',
      zipCode: '500033',
      country: 'India',
    },
    orderStatus: 'CONFIRMED',
    paymentStatus: 'SUCCESS',
    paymentMethod: 'UPI',
    fulfillmentType: 'SINGLE_WAREHOUSE',
    fulfillmentDetails: [
      {
        warehouseId: 'WH-HYD',
        warehouseName: 'Warehouse A – Hyderabad',
        location: 'Madhapur / HITEC City, Hyderabad, Telangana',
        status: 'PENDING_PACKING',
        items: [{ productId: 'PROD-116', productName: 'NeoPhone Prime 128GB', quantity: 1 }],
      },
    ],
    expectedDeliveryDate: '2026-03-12T18:00:00.000Z',
    createdAt: '2026-03-08T09:00:00.000Z',
    updatedAt: '2026-03-08T09:02:00.000Z',
  },
];

export const seedPayments: Payment[] = [
  {
    paymentId: 'PAY-1001',
    orderId: 'ORD-9821',
    amount: 12499,
    paymentMethod: 'UPI',
    paymentStatus: 'SUCCESS',
    transactionId: 'TXN-UPI-982187391',
    paymentDate: '2026-03-01T10:15:22.000Z',
    customerEmail: 'customer@example.com',
  },
  {
    paymentId: 'PAY-1002',
    orderId: 'ORD-9822',
    amount: 92798,
    paymentMethod: 'Credit Card',
    paymentStatus: 'SUCCESS',
    transactionId: 'TXN-CRD-772910382',
    paymentDate: '2026-03-04T12:02:10.000Z',
    customerEmail: 'john@example.com',
  },
  {
    paymentId: 'PAY-1003',
    orderId: 'ORD-9823',
    amount: 28999,
    paymentMethod: 'UPI',
    paymentStatus: 'SUCCESS',
    transactionId: 'TXN-UPI-449102834',
    paymentDate: '2026-03-05T15:21:40.000Z',
    customerEmail: 'sarah@example.com',
  },
  {
    paymentId: 'PAY-1004',
    orderId: 'ORD-9824',
    amount: 251494,
    paymentMethod: 'Credit Card',
    paymentStatus: 'SUCCESS',
    transactionId: 'TXN-CRD-998822110',
    paymentDate: '2026-03-06T11:02:30.000Z',
    customerEmail: 'customer@example.com',
  },
  {
    paymentId: 'PAY-1005',
    orderId: 'ORD-9825',
    amount: 8999,
    paymentMethod: 'UPI',
    paymentStatus: 'SUCCESS',
    transactionId: 'TXN-UPI-123456789',
    paymentDate: '2026-03-07T09:31:00.000Z',
    customerEmail: 'raj@example.com',
  },
  {
    paymentId: 'PAY-1006',
    orderId: 'ORD-9826',
    amount: 3499,
    paymentMethod: 'Debit Card',
    paymentStatus: 'FAILED',
    transactionId: 'TXN-DEB-000999888',
    paymentDate: '2026-03-07T14:01:00.000Z',
    customerEmail: 'priya@example.com',
  },
  {
    paymentId: 'PAY-1007',
    orderId: 'ORD-9827',
    amount: 4999,
    paymentMethod: 'Cash on Delivery',
    paymentStatus: 'SUCCESS',
    transactionId: 'TXN-COD-556677889',
    paymentDate: '2026-03-05T08:05:00.000Z',
    customerEmail: 'vikram@example.com',
  },
  {
    paymentId: 'PAY-1008',
    orderId: 'ORD-9828',
    amount: 11999,
    paymentMethod: 'UPI',
    paymentStatus: 'REFUNDED',
    transactionId: 'TXN-UPI-REF-332211',
    paymentDate: '2026-03-06T15:05:00.000Z',
    customerEmail: 'ananya@example.com',
  },
  {
    paymentId: 'PAY-1009',
    orderId: 'ORD-9829',
    amount: 14299,
    paymentMethod: 'Debit Card',
    paymentStatus: 'SUCCESS',
    transactionId: 'TXN-DEB-443322110',
    paymentDate: '2026-03-04T16:02:00.000Z',
    customerEmail: 'sneha@example.com',
  },
  {
    paymentId: 'PAY-1010',
    orderId: 'ORD-9830',
    amount: 19999,
    paymentMethod: 'UPI',
    paymentStatus: 'SUCCESS',
    transactionId: 'TXN-UPI-990011223',
    paymentDate: '2026-03-08T09:01:30.000Z',
    customerEmail: 'customer@example.com',
  },
];

export const seedNotifications: Notification[] = [
  {
    notificationId: 'NOTIF-01',
    customerId: 'USR-CUST-01',
    orderId: 'ORD-9821',
    message: 'Your order ORD-9821 has been delivered successfully. Thank you for shopping with us!',
    type: 'ORDER_DELIVERED',
    isRead: true,
    createdAt: '2026-03-04T16:30:00.000Z',
  },
  {
    notificationId: 'NOTIF-02',
    customerId: 'USR-CUST-02',
    orderId: 'ORD-9822',
    message: 'Your order ORD-9822 has been SHIPPED from Warehouse A – Hyderabad via Express Surface.',
    type: 'ORDER_SHIPPED',
    isRead: false,
    createdAt: '2026-03-05T09:15:00.000Z',
  },
  {
    notificationId: 'NOTIF-03',
    customerId: 'USR-WM-01',
    orderId: 'ORD-9824',
    warehouseId: 'WH-HYD',
    message: 'Fulfillment Assignment: Pack 2x ProBook Ultra and 3x Tactile Keyboard for Order ORD-9824.',
    type: 'WAREHOUSE_ASSIGNED',
    isRead: false,
    createdAt: '2026-03-06T11:05:00.000Z',
  },
  {
    notificationId: 'NOTIF-04',
    customerId: 'USR-CUST-01',
    orderId: 'ORD-9824',
    message: 'Payment of ₹2,51,494 verified! Order ORD-9824 split across Hyderabad & Vijayawada hubs for fastest dispatch.',
    type: 'PAYMENT_SUCCESS',
    isRead: false,
    createdAt: '2026-03-06T11:06:00.000Z',
  },
  {
    notificationId: 'NOTIF-05',
    customerId: 'USR-ADMIN-01',
    message: 'System Alert: Low stock threshold reached for TurboCharge 100W GaN Wall Charger (3 units remaining).',
    type: 'STOCK_ALERT',
    isRead: false,
    createdAt: '2026-03-07T18:00:00.000Z',
  },
];
